name: Build and deploy the playground
on:
  push:
    branches: [master]
    paths:
      - playground/**
      - .github/workflows/playground.yml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install transpiler dependencies
        working-directory: transpiler
        run: npm ci
      - name: Build transpiler
        working-directory: transpiler
        run: npm run build
      - name: Install playground dependencies
        working-directory: playground
        run: npm ci
      - name: Build playground
        working-directory: playground
        run: npm run build
      - name: Upload playground
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./playground/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1